name: Build

on:
  push:
    branches:
      - main

jobs:
  push-to-github:
    name: Deploy to GitHub registry
    runs-on: ubuntu-latest
    steps:
      - name: Set DOCKER_IMAGE_TAG
        run: echo "DOCKER_IMAGE_TAG=$(date +'%Y%m%d')" >> $GITHUB_ENV

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & Push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ghcr.io/hehmonke/ragemp-server:${{ env.DOCKER_IMAGE_TAG }}
            ghcr.io/hehmonke/ragemp-server:latest
